language: cpp
dist: xenial
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install -y libopenmpi-dev g++-7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 \
                             --slave /usr/bin/g++ g++ /usr/bin/g++-7 
  - sudo update-alternatives --config gcc
  - gcc --version
  - g++ --version
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ctest
