language: cpp
dist: xenial
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libopenmpi-dev gcc-7
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ctest
