language: cpp
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libopenmpi-dev
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ctest

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7